name: Generate Theme Readme
on:
  push:
    branches:
      - main
      - master
    paths:
      - "themes/index.js"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generateThemeDoc:
    runs-on: ubuntu-latest
    name: Generate theme doc

    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # Fix the unsafe repo error which was introduced by the CVE-2022-24765 git patches.
      - name: Fix unsafe repo error
        run: git config --global --add safe.directory ${{ github.workspace }}

      - name: Install dependencies and generate readme
        run: |
          pnpm install --frozen-lockfile
          pnpm run theme-readme-gen
        env:
          CI: true

      - name: Run Script
        uses: skx/github-action-tester@e29768ff4ff67be9d1fdbccd8836ab83233bebb1 # v0.10.0
        with:
          script: ./scripts/push-theme-readme.sh
        env:
          CI: true
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GH_REPO: ${{ secrets.GH_REPO }}
