name: Close stale theme pull requests that have the 'invalid' label.
on:
  # Temporary disabled due to paused themes addition.
  # See: https://github.com/dytsou/github-readme-stats/issues/3404
  # schedule:
  #   #        ┌───────────── minute (0 - 59)
  #   #        │ ┌───────────── hour (0 - 23)
  #   #        │ │  ┌───────────── day of the month (1 - 31)
  #   #        │ │  │  ┌───────────── month (1 - 12 or JAN-DEC)
  #   #        │ │  │  │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #   #        │ │  │  │ │
  #   #        │ │  │  │ │
  #   #        │ │  │  │ │
  #   #        * *  *  * *
  #   - cron: "0 0 */7 * *"
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  closeOldThemePrs:
    if: github.repository == 'dytsou/github-readme-stats'
    name: Close stale 'invalid' theme PRs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Close stale theme PRs
        run: pnpm run close-stale-theme-prs
        env:
          STALE_DAYS: 20
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
